# Application port.
server:
  port: 9101

# The preconfigured set of movie cosine vectors.
app:
  dataset: zippy-quotes.txt

# Registers Sequential Application with Eureka.
eureka:
  client:
    enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka

# Use H2 datasource.
spring:
  application:
    name: zippy
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
      jdbc:
        time_zone: UTC
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        show_sql: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
#  datasource:
#    url=jdbc:h2:mem:movie;DB_CLOSE_ON_EXIT=TRUE:
